# -*- coding: utf-8 -*-
"""PasswordGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y57RocqIO1KxEcBn3kP5pRf_fHuXYCst
"""

import random as r      #importing random library in the program as r

#intializing all the variables with the characters that can be used in the password
lower="abcdefghijklmnopqrstuvwxyz"
upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
num="0123456789"
special_char="[]{}()*;/,-%#@!"

all = lower+upper+num+special_char    #merging all the character list into single list

length=12         #defining the length of password to be generated
password="".join(r.sample(all,length))  #using random function to select characters from the list and storing final password

print(password)     #printing the final result

